FROM golang:1.20.5
WORKDIR '/github.com/mtfelian/filesystem'
COPY go.* .
RUN --mount=type=cache,target=/root/go/pkg/mod \
    go mod download
COPY . .
RUN --mount=type=cache,target=/root/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    go install github.com/onsi/ginkgo/ginkgo@v1.16.5 && \
    ginkgo build
CMD ["sh", "-c", "ginkgo -race filesystem.test"]